language: node_js
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    node_js: 10
  - os: osx
    node_js: 10
addons:
  chrome: stable
  firefox: latest
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=google-chrome-stable; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
- travis_retry npm run ci
before_deploy:
- sed -i 's/"private":\ true/"private":\ false/' package.json
- sed -i -E 's/^dist\/?.*$//' .gitignore
deploy:
  provider: npm
  email:
    secure: ww1P29w6mvispNikPUBhc9iFsc0sYlFNA+aOwsLxl46p2+Jxmb9xlsP2pweswIpQMFzT+SIeFcnqzflfUkmYSN9J5ULHLjAiDptPkzv0dzAAI2VewjiADYdG/Ii/ujdjXGWfFIutwUt6tHlMc3l6Jjlk4RvW3PD0H25f5M5hZz6Jbky8FrQ6z9PKQYUJcDgnW2pg7V7lBssyY8a2gJBRvVJeAR7bMwDGRdxedBdXj3e6CE8SjWdd388yQcJhSdx6JRgim/FNx/05PIElDgZzaaKjzMUNCvYcC1tHNLqmqolKanenWv3OXaEEEcq0p4HmRIWXREOVtkJIbG8vr+lDy7a3YydrTZVZYSKZXS1CtzJFrGLYu4R2NsISLArnftZxK+e2VyzXbpMoiojYgZWcNAbDfY3X9RMxumTc99Rm7zN4iQ3NQOUa9YuQVqRkmCVLsw2XHSqgtpqVDFmpxpuZbi2Kpfyol6ZE4uh12uLehiq/3MYZlPYjmVds1qyYNZLyViu/N3zTw2BuT+tSTT6KIS1a6BeBY6Pq2M5A4dTCu6Xgtd0WXExLHtS1KnQcxbpADjoWD6uQvNspK3s6fbCGBZu08LeSNag7mkgielxIM0jLweknyNX9VlFVNg58R2ZJsMpHjfnUVEIqbhvGx3gmo9vgUbgoHahUkwy98GFr8x0=
  api_key:
    secure: "tvB5ZKVbzYmLakrVbgWYV3ADR7xmMeTaCppjEci9tD1MQpxZJ2HEWPUAuGt0YoElzDb92nwLFgMll1nPWv3vlWFTe4IddGHpOqwmhRNRZnMsRhg1+lJNvLrpL3XjUUkc6sFB4yWbjN72k3my1a8IhdifuOHbWAucVgdrN8Ics7uangFZdEtRswzA3wiReVqVs0uJlLoMxYuIPrYPS5MHB0X5nSxq0Qf623InXDKXBJUJjr5wyErNMejMbGT5y8RYCZ5yb3DqGEFr7mCETYLX8txtBnB4UrxtqjJO8y0TLXSgjcBj+XBB6SbiAVFCRlCm9wuuWwO4LQbRB/3QtnErWHPlPkiooNznxSides8l6f0pw6qgIqM59rOuF+juTl8LzdGPvvQDxzPxFkqjtIjx/5TlA9jjnrFgMa94Uci640drWdB61kJRjlIW6FZ8snRPPOGDbWXhtMduzlBGxSZjPJJMwSi5FtnDefP4T20rt4BQcYRU474cISqSIyV0S9tkRVmsymlCIX0vOB9Rf0oWTYRucwlbsqtsFjTQFrkLsMFeGoqj4uZW/1Ezoi5o6J88XceFrAu6E1eGqa4/iduCJSaqD+xB/NDXdrKWR4kXCwq37jXRZRGaBTr56KiDFDUPbD95xLsIpEfooyx3Ah1VCkkNdEqr8D8o3CSJ8VEaYK0="
  on:
    branch: master
    node: 10
    condition: $TRAVIS_OS_NAME = linux
  skip_cleanup: true
notifications:
  email:
    recipients:
    - secure: ww1P29w6mvispNikPUBhc9iFsc0sYlFNA+aOwsLxl46p2+Jxmb9xlsP2pweswIpQMFzT+SIeFcnqzflfUkmYSN9J5ULHLjAiDptPkzv0dzAAI2VewjiADYdG/Ii/ujdjXGWfFIutwUt6tHlMc3l6Jjlk4RvW3PD0H25f5M5hZz6Jbky8FrQ6z9PKQYUJcDgnW2pg7V7lBssyY8a2gJBRvVJeAR7bMwDGRdxedBdXj3e6CE8SjWdd388yQcJhSdx6JRgim/FNx/05PIElDgZzaaKjzMUNCvYcC1tHNLqmqolKanenWv3OXaEEEcq0p4HmRIWXREOVtkJIbG8vr+lDy7a3YydrTZVZYSKZXS1CtzJFrGLYu4R2NsISLArnftZxK+e2VyzXbpMoiojYgZWcNAbDfY3X9RMxumTc99Rm7zN4iQ3NQOUa9YuQVqRkmCVLsw2XHSqgtpqVDFmpxpuZbi2Kpfyol6ZE4uh12uLehiq/3MYZlPYjmVds1qyYNZLyViu/N3zTw2BuT+tSTT6KIS1a6BeBY6Pq2M5A4dTCu6Xgtd0WXExLHtS1KnQcxbpADjoWD6uQvNspK3s6fbCGBZu08LeSNag7mkgielxIM0jLweknyNX9VlFVNg58R2ZJsMpHjfnUVEIqbhvGx3gmo9vgUbgoHahUkwy98GFr8x0=
    on_success: change
    on_failure: always
